config/routes.rb
Fleet::Application.routes.draw do
  resources :vehicles
  resources :maintenance, :only => [:index, :new, :create]

  root :to => 'pages#home'

  match '/vehicles' => 'vehicles#index'
  match '/vehicles/:id' => 'vehicles#show'
  match '/maintenance' => 'maintenance#index'
  match '/maintenance/:id' => 'maintenance#show'
  match '/reports' => 'pages#reports'
  match '/signin' => 'pages#signin'

end

app/models/driver.rb
class Driver < ActiveRecord::Base
  attr_accessible :fname, :lname
  
  has_many :vehicles
  
  validates :fname, :lname, :presence => true
end

app/models/maintenance.rb
class Maintenance < ActiveRecord::Base
  attr_accessible :invoice, :date, :milage, :cost, :serviced_by, :category, :description
  belongs_to :vehicles
  
  date_format = /\d{2}\-\d{2}\-\d{4}/
  cost_format = /\A\d+\.\d{2}\z/
  
  validates :invoice, :milage, :serviced_by, :category, :description, :presence => true
  validates :date, :format => { :with => date_format }, :presence => true
  validates :cost, :format => { :with => cost_format }, :presence => true
end

app/models/vehicles.rb
class Vehicles < ActiveRecord::Base
  attr_accessible :plate, :status, :vin, :make, :model, :year
  
  belongs_to :driver
  has_many :maintenances
  
  make_regex = /[a-z]*/i
  
  validates :vin, :length => {:is => 17}
  validates :plate, :length => { :minimum => 5, :maximum => 7 }, :allow_nil => false
  validates :make, :model, :status, :presence => true
  validates_length_of :year, :is => 4
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/maintenance_controller.rb
class MaintenanceController < ApplicationController
    def index
      @maints = Maintenance.all    
      @title = "Maintenance"        
    end

    def new
      @title = "Enter Workorder"
      @new_maint = Maintenance.new    

    end

   def create
      @maint = Maintenance.new(params[:maint])
       if @maint.save
         redirect_to @maint, :flash => {:success => "New maintenance record created" }
       else
         render 'new'
       end
    end

    def destroy

    end

    def edit

    end
  end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def vehicles    
    @title = "Vehicles"
  end

  def maintenance
    @title = "Maintenance"
  end

  def home
  end

end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  def index
    @vehicles = Vehicles.all
    @title = "Vehicles"
  end

  def new
    @vehicle = Vehicles.new
    @title = "New Vehicle"
  end
  
  def show
    @vehicles = Vehicles.find(params[:id])
    @title = @vehicle.year
  end
  
  def create
    @vehicle = Vehicles.new(params[:vehicles])
    if @vehicle.save
      redirect_to @vehicle
    else
      render 'new'
    end  
  end
  
  def destroy
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def title
    base_title = "TETCO Fleet Management"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
  
  def logo
    logo = image_tag("logo.png", :alt => "TETCO Fleet Management", :class => "box")
  end
end

app/helpers/maintenance_helper.rb
module MaintenanceHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/layouts/_header.html.erb
<header>
	<div class="section">
	<%= link_to logo, root_path %>
	<nav class="box">
		<%= link_to 'MAINT', maintenance_path %>
		<%= link_to 'VEHICLES', vehicles_path %>
		<%= link_to 'REPORTS', reports_path %>
		<%= link_to 'SIGN IN', signin_path %>
	</nav>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="container">
<%= render 'layouts/header' %>

<%= yield %>

</body>
</html>

app/views/maintenance/_new_maintenance.html.erb
<% form_for(:maintenance)  do |f| %>
	<div class="field">
		<%= f.label :invoice %> 
		<%= f.text_field :invoice %><br>
	</div>	
	<div class="field">
		<%= f.label :date %> 
		<%= f.text_field :date %><br>
	</div>	
	<div class="field">
		<%= f.label :milage %> 
		<%= f.text_field :milage %><br>
	</div>	
	<div class="field">
		<%= f.label :serviced_by %> 
		<%= f.text_field :serviced_by %><br>
	</div>	
	<div class="field">
		<%= f.label :cost %> 
		<%= f.text_field :cost %><br>
	</div>	
	<div class="field">
		<%= f.label :description %> 
		<%= f.text_field :description %><br>
	</div>
	<div class="field">
		<%= f.label :category %> 
		<%= f.text_field :category %><br>
	</div>
	<div class="actions">
		<%= f.submit "Submit" %>
	</div>
<% end %>

app/views/maintenance/create.html.erb
<h1>Maintenance#create</h1>
<p>Find me in app/views/maintenance/create.html.erb</p>

app/views/maintenance/destroy.html.erb
<h1>Maintenance#destroy</h1>
<p>Find me in app/views/maintenance/destroy.html.erb</p>

app/views/maintenance/index.html.erb
<h1>Maintenance Log</h1>

<p>What'd you fix son?</p>
<%= render 'new_maintenance' %>
<br><table class="sidebar">
	<% @maints.each do |m| %>
	<tr>
		<td><%= link_to m.invoice, m.invoice %></td>
		<td><%= m.date %></td>
		<td><%= m.category %></td>
		<td><%= m.serviced_by %></td>
		<td>$<%= m.cost %></td>
	</tr>
	<% end %>
</table>

app/views/maintenance/new.html.erb
<!-- <h2>Work Order Entry</h2>

<div class="maint_new">
<% form_for @new_maint  do |f| %>
	<div class="field">
		<%= f.label :invoice %> 
		<%= f.text_field :invoice %><br>
	</div>	
	<div class="field">
		<%= f.label :date %> 
		<%= f.text_field :date %><br>
	</div>	
	<div class="field">
		<%= f.label :milage %> 
		<%= f.text_field :milage %><br>
	</div>	
	<div class="field">
		<%= f.label :serviced_by %> 
		<%= f.text_field :serviced_by %><br>
	</div>	
	<div class="field">
		<%= f.label :cost %> 
		<%= f.text_field :cost %><br>
	</div>	
	<div class="field">
		<%= f.label :desc %> 
		<%= f.text_field :desc %><br>
	</div>
	<div class="field">
		<%= f.label :desc %> 
		<%= f.text_field :desc %><br>
	</div>	
	<div class="field">
		<%= f.label :category %> 
		<%= f.text_field :category %><br>
	</div>
	<div class="actions">
		<%= f.submit "Submit" %>
	</div>	
<% end %>
</div> -->

app/views/maintenance/show.html.erb
show me your moves

app/views/pages/home.html.erb
<h1 align="center">TETCO Fleet Management</h1>
<br>
<menu>
	<%= link_to "MAINTENANCE", maintenance_path %>
	<%= link_to "VEHICLES", vehicles_path %>
	<%= link_to "REPORTS", reports_path %>
<menu>
<br>
<div class="slogan">Keeping your shit fresh since 1984</div>

app/views/pages/maintenance.html.erb
<h1>Pages#maintenance</h1>
<p>Find me in app/views/pages/maintenance.html.erb</p>

app/views/pages/reports.html.erb
Future site of reports

app/views/pages/signin.html.erb
Eventually this will be AJAX SON

app/views/pages/vehicles.html.erb
<h1>Pages#vehicles</h1>
<p>Find me in app/views/pages/vehicles.html.erb</p>

app/views/vehicles/_sidebar.html.erb
<table class="sidebar">
	<% @vehicles.each do |vehicle| %>
		<tr>
			<td><%= link_to vehicle.plate.upcase, vehicle %></td>
			<td><%= vehicle.year %> <%= vehicle.make.upcase.humanize %> <%= vehicle.model.capitalize %></td>
	<% end %>
</table>

app/views/vehicles/create.html.erb
<h1>Vehicles#create</h1>
<p>Find me in app/views/vehicles/create.html.erb</p>

app/views/vehicles/destroy.html.erb
<h1>Vehicles#destroy</h1>
<p>Find me in app/views/vehicles/destroy.html.erb</p>

app/views/vehicles/index.html.erb
<h1>Vehicle Registry</h1>

<p>Ghost ride the whip</p>

<%= link_to "Create new vehicle", 'vehicles/new' %>

<%= render 'sidebar' %>

app/views/vehicles/new.html.erb
<div class="vehicle_new">
<%= form_for(:vehicles) do |f| %>
	<div class="field">
		<%= f.label :make %> 
		<%= f.text_field :make %><br>
	</div>	
	<div class="field">
		<%= f.label :model %> 
		<%= f.text_field :model %><br>
	</div>	
	<div class="field">
		<%= f.label :year %> 
		<%= f.text_field :year %><br>
	</div>	
	<div class="field">
		<%= f.label :plate %> 
		<%= f.text_field :plate %><br>
	</div>	
	<div class="field">
		<%= f.label :vin %> 
		<%= f.text_field :vin %><br>
	</div>	
	<div class="field">
		<%= f.label :status %> 
		<%= f.text_field :status %><br>
	</div>	
	<div class="actions">
		<%= f.submit "Submit" %>
	</div>	
<% end %>
</div>

app/views/vehicles/show.html.erb
<h2><%= @vehicle.year %> <%= @vehicle.make.capitalize %> <%= @vehicle.model.capitalize %></h2>

<h3>Status: <%= @vehicle.status.upcase %></h3>
<table class="vehicle">
	<tr>
		<td>Plate: </td>
		<td><%= @vehicle.plate.upcase %></td>
	</tr>
	<tr>
		<td>VIN: </td>
		<td><%= @vehicle.vin.upcase %></td>
	</tr>
</table>

<%= render 'sidebar' %>